# Generated by Django 4.2 on 2023-10-09 19:40

from django.db import migrations, models
import menus.models


class Migration(migrations.Migration):
    dependencies = [
        ("menus", "0002_category_menuitem_image_menuitem_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="componentchoises",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=menus.models.ingredient_image_path
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="images/{self.name}/"
            ),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=menus.models.item_image_path
            ),
        ),
    ]
