# Generated by Django 4.2 on 2023-10-10 22:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("menus", "0003_componentchoises_image_alter_category_image_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="menuitem",
            name="sale_price",
        ),
        migrations.AddField(
            model_name="menuitem",
            name="sale",
            field=models.FloatField(
                blank=True,
                default=1,
                null=True,
                validators=[
                    django.core.validators.MaxValueValidator(1),
                    django.core.validators.MinValueValidator(0),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="images/categories/"
            ),
        ),
    ]
