# Generated by Django 4.2 on 2023-10-11 19:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("menus", "0004_remove_menuitem_sale_price_menuitem_sale_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menuitemingredient",
            name="quantity",
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
    ]
