# Generated by Django 4.2 on 2023-10-10 22:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="code",
            field=models.CharField(default="7D25DA5EA883DFB", max_length=15),
        ),
        migrations.AlterField(
            model_name="order",
            name="received_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
