# Generated by Django 4.2 on 2023-10-11 01:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("menus", "0004_remove_menuitem_sale_price_menuitem_sale_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("orders", "0002_alter_order_code_alter_order_received_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(default="F419B49D1", max_length=9)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("In_Progress", "In_Progress"),
                            ("Submited", "Submited"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="order",
            name="total",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="code",
            field=models.CharField(default="7E93FD7837F89A2", max_length=15),
        ),
        migrations.AlterField(
            model_name="orderitemdetail",
            name="item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="order_item",
                to="menus.menuitem",
            ),
        ),
        migrations.AlterField(
            model_name="orderitemdetail",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order",
                to="orders.order",
            ),
        ),
        migrations.CreateModel(
            name="CartItemDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "cart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cart",
                        to="orders.cart",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cart_item",
                        to="menus.menuitem",
                    ),
                ),
            ],
        ),
    ]
