# Generated by Django 4.2 on 2023-10-14 15:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0002_alter_cart_code_alter_order_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="tax",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cart",
            name="code",
            field=models.CharField(default="56B7BA623", max_length=9),
        ),
        migrations.AlterField(
            model_name="order",
            name="code",
            field=models.CharField(default="7E5BA3C8537B33A", max_length=15),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("In_Progress", "In_Progress"),
                    ("Submited", "Submited"),
                    ("Canceled", "Canceled"),
                    ("Delivered", "Delivered"),
                ],
                max_length=20,
            ),
        ),
    ]
