# Generated by Django 4.2 on 2023-10-15 22:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0002_alter_cart_code_alter_order_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="code",
            field=models.CharField(default="C3D2FBBBA", max_length=9),
        ),
        migrations.AlterField(
            model_name="order",
            name="code",
            field=models.CharField(default="E9FEFFB4B77F596", max_length=15),
        ),
    ]
