# Generated by Django 4.2 on 2023-10-16 20:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0004_alter_cart_code_alter_order_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="code",
            field=models.CharField(default="8523565A8", max_length=9),
        ),
        migrations.AlterField(
            model_name="order",
            name="code",
            field=models.CharField(default="1AD3A135EAA1EC6", max_length=15),
        ),
        migrations.DeleteModel(
            name="ChosenComponent",
        ),
    ]
