# Generated by Django 4.2 on 2023-10-16 21:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0006_alter_cart_code_alter_customization_ingredient_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="code",
            field=models.CharField(default="FBBBA563E", max_length=9),
        ),
        migrations.AlterField(
            model_name="order",
            name="code",
            field=models.CharField(default="21A2F52D88BADCF", max_length=15),
        ),
        migrations.DeleteModel(
            name="Customization",
        ),
    ]
