# Generated by Django 4.2 on 2023-10-16 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("menus", "0004_menuitem_is_fav_alter_menuitem_sale"),
        ("orders", "0008_alter_cart_code_alter_order_code_customization"),
    ]

    operations = [
        migrations.AddField(
            model_name="customization",
            name="component",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="menus.componentchoises",
            ),
        ),
        migrations.AlterField(
            model_name="cart",
            name="code",
            field=models.CharField(default="421C3E374", max_length=9),
        ),
        migrations.AlterField(
            model_name="order",
            name="code",
            field=models.CharField(default="9E845ECFE355BCD", max_length=15),
        ),
    ]
