# Generated by Django 4.2 on 2023-10-17 00:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0009_customization_component_alter_cart_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="code",
            field=models.CharField(default="D1519ADBE", max_length=9),
        ),
        migrations.AlterField(
            model_name="order",
            name="code",
            field=models.CharField(default="B5C6A7D4C4295EF", max_length=15),
        ),
    ]
