# Generated by Django 4.2 on 2023-10-17 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0010_alter_cart_code_alter_order_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="SpecialInstructions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("delivery_instraction", models.CharField(max_length=100)),
                ("save_for_future", models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name="cart",
            name="code",
            field=models.CharField(default="C1B74BC73", max_length=9),
        ),
        migrations.AlterField(
            model_name="order",
            name="code",
            field=models.CharField(default="4FB9911E2C29533", max_length=15),
        ),
        migrations.AddField(
            model_name="cart",
            name="special_instructions",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cart_special_instractions",
                to="orders.specialinstructions",
            ),
        ),
    ]
