# Generated by Django 4.2 on 2023-10-17 22:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "orders",
            "0011_specialinstructions_alter_cart_code_alter_order_code_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="specialinstructions",
            old_name="delivery_instraction",
            new_name="instraction",
        ),
        migrations.AlterField(
            model_name="cart",
            name="code",
            field=models.CharField(default="4B8C1D9B4", max_length=9),
        ),
        migrations.AlterField(
            model_name="order",
            name="code",
            field=models.CharField(default="EB6A6F4C925F7AE", max_length=15),
        ),
    ]
