# Generated by Django 4.2 on 2023-10-17 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "orders",
            "0012_rename_delivery_instraction_specialinstructions_instraction_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="special_instructions",
        ),
        migrations.AddField(
            model_name="specialinstructions",
            name="cart",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cart_instructions",
                to="orders.cart",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="cart",
            name="code",
            field=models.CharField(default="9A7773A79", max_length=9),
        ),
        migrations.AlterField(
            model_name="order",
            name="code",
            field=models.CharField(default="BB4593BC73CAF4A", max_length=15),
        ),
    ]
