# Generated by Django 4.2 on 2023-10-18 15:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0013_remove_cart_special_instructions_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="specialinstructions",
            name="cutlery",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="specialinstructions",
            name="ketchup",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="cart",
            name="code",
            field=models.CharField(default="8B4EB9C2F", max_length=9),
        ),
        migrations.AlterField(
            model_name="order",
            name="code",
            field=models.CharField(default="96C9D427E88771E", max_length=15),
        ),
        migrations.AlterField(
            model_name="specialinstructions",
            name="instraction",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="specialinstructions",
            name="save_for_future",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
